// AUTO-GENERATED by scripts/build_track_profiles.py — edit the table there, not this file.
// Shared by daily_racing_analyzer.html and engine/emerald_engine.py.
window._trackProfiles={
 "aintree": {
  "camber": 0.1,
  "caution_flags": [
   "poor_jumper"
  ],
  "circuit_f": 16,
  "circumference_furlongs": 16,
  "codes": "nh",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Aintree",
  "running_styles": [
   "bold_jumper",
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.2,
  "significant_features": [
   "Flat, galloping — long run-in",
   "Grand National and Mildmay courses"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 4,
  "surface": "turf",
  "undulation": 0.1,
  "uphill_finish": 0.05,
  "wants": [
   "Stamina",
   "Bold jumping over the National fences"
  ]
 },
 "ascot": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 14,
  "circumference_furlongs": 14,
  "codes": "both",
  "conf": "high",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "1m+": "negligible",
   "5f": "high_draw_slight",
   "6f": "slight"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "triangle",
  "name": "Ascot",
  "running_styles": [
   "galloper",
   "strong_traveller"
  ],
  "shape": "triangle",
  "sharpness": 0.35,
  "significant_features": [
   "Right-handed triangle with a straight mile",
   "Uphill finish — testing track"
  ],
  "stalls": [],
  "straight_course_f": 8,
  "straight_f": 2.5,
  "surface": "turf",
  "undulation": 0.55,
  "uphill_finish": 0.6,
  "wants": [
   "Class and stamina — stiff finish"
  ]
 },
 "ayr": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "both",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Ayr",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.3,
  "significant_features": [
   "Flat, fair, galloping left-hander",
   "Straight 6f — big sprint fields split"
  ],
  "stalls": [],
  "straight_course_f": 6,
  "straight_f": 4,
  "surface": "turf",
  "undulation": 0.1,
  "uphill_finish": 0.05,
  "wants": [
   "Galloping types"
  ]
 },
 "ballinrobe": {
  "camber": 0.25,
  "caution_flags": [
   "large_striding_horse",
   "hold_up_horse"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "tight_oval",
  "name": "Ballinrobe",
  "running_styles": [
   "prominent",
   "front_runner"
  ],
  "shape": "tight_oval",
  "sharpness": 0.75,
  "significant_features": [
   "Right-handed, sharp"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 1.5,
  "surface": "turf",
  "undulation": 0.3,
  "uphill_finish": 0.2,
  "wants": [
   "Handy, quick types"
  ]
 },
 "bangor on dee": {
  "camber": 0.2,
  "caution_flags": [],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "pear",
  "name": "Bangor-on-Dee",
  "running_styles": [
   "prominent"
  ],
  "shape": "pear",
  "sharpness": 0.6,
  "significant_features": [
   "Left-handed, sharp, no grandstand"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.1,
  "uphill_finish": 0.05,
  "wants": [
   "Handy types"
  ]
 },
 "bath": {
  "camber": 0.35,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Bath",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.45,
  "significant_features": [
   "Left-handed, undulating hill-top track",
   "Kink in the straight, rising finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 4,
  "surface": "turf",
  "undulation": 0.6,
  "uphill_finish": 0.55,
  "wants": [
   "Handles undulations, stamina"
  ]
 },
 "bellewstown": {
  "camber": 0.35,
  "caution_flags": [
   "large_striding_horse",
   "hold_up_horse"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   52,
   57,
   55,
   48,
   44,
   47,
   53,
   57,
   58,
   60
  ],
  "layout": "tight_oval",
  "name": "Bellewstown",
  "running_styles": [
   "prominent",
   "front_runner"
  ],
  "shape": "tight_oval",
  "sharpness": 0.8,
  "significant_features": [
   "Left-handed, sharp and undulating hill-top track"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 1.5,
  "surface": "turf",
  "undulation": 0.65,
  "uphill_finish": 0.55,
  "wants": [
   "Very handy, balanced types"
  ]
 },
 "beverley": {
  "camber": 0.2,
  "caution_flags": [
   "large_striding_horse",
   "non_stayer_uphill"
  ],
  "circuit_f": 11,
  "circumference_furlongs": 11,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "1m+": "low_draw_slight",
   "5f": "high_draw_moderate",
   "7f": "low_draw_slight"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Beverley",
  "running_styles": [
   "prominent",
   "handy"
  ],
  "shape": "oval",
  "sharpness": 0.65,
  "significant_features": [
   "Right-handed, tricky home turn",
   "Stiff uphill 5f course"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2.5,
  "surface": "turf",
  "undulation": 0.55,
  "uphill_finish": 0.75,
  "wants": [
   "Handy types",
   "Stamina for the stiff 5f uphill finish"
  ]
 },
 "brighton": {
  "camber": 0.7,
  "caution_flags": [
   "unbalanced_mover",
   "large_striding_horse"
  ],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   60,
   56,
   51,
   46,
   42,
   40,
   44,
   50,
   56,
   62
  ],
  "layout": "horseshoe",
  "name": "Brighton",
  "running_styles": [
   "prominent",
   "front_runner"
  ],
  "shape": "horseshoe",
  "sharpness": 0.55,
  "significant_features": [
   "Left-handed horseshoe, big gradients and camber",
   "Downhill then rising finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 3.5,
  "surface": "turf",
  "undulation": 0.9,
  "uphill_finish": 0.4,
  "wants": [
   "Balanced, handy types"
  ]
 },
 "carlisle": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 13,
  "circumference_furlongs": 13,
  "codes": "both",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "pear",
  "name": "Carlisle",
  "running_styles": [
   "stayer"
  ],
  "shape": "pear",
  "sharpness": 0.35,
  "significant_features": [
   "Right-handed, undulating",
   "Stiff uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 3.5,
  "surface": "turf",
  "undulation": 0.6,
  "uphill_finish": 0.75,
  "wants": [
   "Stamina — stiff uphill finish"
  ]
 },
 "cartmel": {
  "camber": 0.3,
  "caution_flags": [
   "large_striding_horse"
  ],
  "circuit_f": 8,
  "circumference_furlongs": 8,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "tight_oval",
  "name": "Cartmel",
  "running_styles": [
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.9,
  "significant_features": [
   "Very sharp left-hander",
   "Very long run-in (about half a mile)"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 4,
  "surface": "turf",
  "undulation": 0.5,
  "uphill_finish": 0.3,
  "wants": [
   "Very handy types"
  ]
 },
 "catterick": {
  "camber": 0.25,
  "caution_flags": [
   "large_striding_horse",
   "hold_up_horse"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "both",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "5f": "low_draw_moderate",
   "6f": "low_draw_slight"
  },
  "elevation": [
   66,
   63,
   60,
   57,
   54,
   51,
   48,
   46,
   44,
   42
  ],
  "layout": "tight_oval",
  "name": "Catterick",
  "running_styles": [
   "front_runner",
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.8,
  "significant_features": [
   "Tight left-hander, downhill 5f",
   "Speed favoured"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.45,
  "uphill_finish": 0.1,
  "wants": [
   "Early speed, handiness"
  ]
 },
 "chelmsford city": {
  "camber": 0.15,
  "caution_flags": [
   "large_striding_horse"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "flat",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "5f": "low_draw_slight",
   "6f": "low_draw_slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Chelmsford City",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.6,
  "significant_features": [
   "Left-handed Polytrack oval"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "aw",
  "undulation": 0.0,
  "uphill_finish": 0.0,
  "wants": [
   "Tactical speed"
  ]
 },
 "cheltenham": {
  "camber": 0.3,
  "caution_flags": [
   "non_stayer_uphill",
   "poor_jumper"
  ],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "nh",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Cheltenham",
  "running_styles": [
   "prominent",
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.4,
  "significant_features": [
   "Left-handed, undulating (Old and New courses)",
   "Stiff uphill finish up the hill",
   "Downhill fences test jumping"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 3,
  "surface": "turf",
  "undulation": 0.8,
  "uphill_finish": 0.9,
  "wants": [
   "Stamina — famous uphill finish",
   "Accurate jumping downhill"
  ]
 },
 "chepstow": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 16,
  "circumference_furlongs": 16,
  "codes": "both",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   52,
   57,
   55,
   48,
   44,
   47,
   53,
   57,
   58,
   60
  ],
  "layout": "oval",
  "name": "Chepstow",
  "running_styles": [
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.3,
  "significant_features": [
   "Left-handed, very undulating"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 5,
  "surface": "turf",
  "undulation": 0.85,
  "uphill_finish": 0.55,
  "wants": [
   "Stamina, handles gradients"
  ]
 },
 "chester": {
  "camber": 0.45,
  "caution_flags": [
   "large_striding_horse",
   "hold_up_horse",
   "high_draw_sprint"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "1m2f+": "negligible",
   "5f": "low_draw_strong",
   "6f": "low_draw_moderate",
   "7f": "low_draw_slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "circle",
  "name": "Chester",
  "running_styles": [
   "front_runner",
   "prominent"
  ],
  "shape": "circle",
  "sharpness": 0.98,
  "significant_features": [
   "Extremely sharp left-hand turns throughout",
   "Draw critical at sprint distances — low numbers heavily favoured",
   "Front-runners dominate due to tight bends",
   "Big-striding galloping types disadvantaged"
  ],
  "stalls": [
   [
    "5f",
    "Inside rail",
    "Low draw ++"
   ],
   [
    "6f",
    "Inside rail",
    "Low draw +"
   ],
   [
    "7f–1m",
    "Inside rail",
    "Low slight"
   ],
   [
    "1m2f+",
    "Inside rail",
    "Negligible"
   ]
  ],
  "straight_course_f": 0,
  "straight_f": 1,
  "surface": "turf",
  "undulation": 0.1,
  "uphill_finish": 0.0,
  "wants": [
   "Small, handy, quick-actioned",
   "Early speed to hold a position",
   "Low draw at sprint trips"
  ]
 },
 "clonmel": {
  "camber": 0.25,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 11,
  "circumference_furlongs": 11,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Clonmel",
  "running_styles": [
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.45,
  "significant_features": [
   "Right-handed, undulating",
   "Stiff uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.6,
  "uphill_finish": 0.65,
  "wants": [
   "Stamina — uphill finish"
  ]
 },
 "cork": {
  "camber": 0.15,
  "caution_flags": [],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Cork",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.35,
  "significant_features": [
   "Right-handed (Mallow)",
   "Fairly flat, fair track"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2.5,
  "surface": "turf",
  "undulation": 0.25,
  "uphill_finish": 0.25,
  "wants": [
   "Fair galloping test"
  ]
 },
 "curragh": {
  "camber": 0.2,
  "caution_flags": [
   "sharp_track_specialist",
   "non_stayer_uphill"
  ],
  "circuit_f": 16,
  "circumference_furlongs": 16,
  "codes": "flat",
  "conf": "high",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "1m": "varies_with_stalls_side",
   "1m2f+": "negligible",
   "5f": "varies_with_stalls_side",
   "6f": "varies_with_stalls_side",
   "7f": "varies_with_stalls_side"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "horseshoe",
  "name": "Curragh",
  "running_styles": [
   "galloper",
   "strong_traveller"
  ],
  "shape": "horseshoe",
  "sharpness": 0.15,
  "significant_features": [
   "Wide, galloping right-handed horseshoe",
   "Straight course up to 1m — big fields split into groups",
   "Rising finish rewards genuine stayers"
  ],
  "stalls": [
   [
    "5f–1m",
    "Straight course — stands or far side (set per meeting)",
    "Runners drawn next to the stalls rail"
   ],
   [
    "1m1f+",
    "Round course, inside rail",
    "Negligible"
   ]
  ],
  "straight_course_f": 8,
  "straight_f": 3,
  "surface": "turf",
  "undulation": 0.35,
  "uphill_finish": 0.35,
  "wants": [
   "Galloping, long-striding types",
   "Stamina for a stiff finish",
   "Class — home of the Irish Classics"
  ]
 },
 "doncaster": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 16,
  "circumference_furlongs": 16,
  "codes": "both",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "1m+": "negligible",
   "5f": "varies_with_stalls_side"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "pear",
  "name": "Doncaster",
  "running_styles": [
   "galloper"
  ],
  "shape": "pear",
  "sharpness": 0.2,
  "significant_features": [
   "Wide, flat, galloping pear-shaped track",
   "Straight mile"
  ],
  "stalls": [],
  "straight_course_f": 8,
  "straight_f": 4.5,
  "surface": "turf",
  "undulation": 0.1,
  "uphill_finish": 0.05,
  "wants": [
   "Galloping types",
   "Stamina at 1m6f+"
  ]
 },
 "down royal": {
  "camber": 0.15,
  "caution_flags": [
   "sharp_track_specialist"
  ],
  "circuit_f": 15,
  "circumference_furlongs": 15,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Down Royal",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.25,
  "significant_features": [
   "Right-handed, galloping (Northern Ireland)",
   "Fairly flat, fair test"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 3,
  "surface": "turf",
  "undulation": 0.25,
  "uphill_finish": 0.2,
  "wants": [
   "Galloping types"
  ]
 },
 "downpatrick": {
  "camber": 0.35,
  "caution_flags": [
   "non_stayer_uphill",
   "large_striding_horse"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   60,
   56,
   51,
   46,
   42,
   40,
   44,
   50,
   56,
   62
  ],
  "layout": "oval",
  "name": "Downpatrick",
  "running_styles": [
   "prominent",
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.7,
  "significant_features": [
   "Right-handed, very undulating (Northern Ireland)",
   "Very stiff uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 1.5,
  "surface": "turf",
  "undulation": 0.8,
  "uphill_finish": 0.8,
  "wants": [
   "Stamina — very stiff uphill finish",
   "Handy types"
  ]
 },
 "dundalk": {
  "camber": 0.25,
  "caution_flags": [
   "high_draw_sprint",
   "hold_up_horse"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "flat",
  "conf": "high",
  "country": "IRE",
  "direction": "L",
  "draw_bias": {
   "1m+": "low_draw_slight",
   "5f": "low_draw_strong",
   "6f": "low_draw_moderate",
   "7f": "low_draw_slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "tight_oval",
  "name": "Dundalk (AW)",
  "running_styles": [
   "front_runner",
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.8,
  "significant_features": [
   "Ireland's all-weather track",
   "Tight left-handed oval with banked bends",
   "Pace and position are key"
  ],
  "stalls": [
   [
    "5f",
    "Inside rail",
    "Low draw ++"
   ],
   [
    "6f–7f",
    "Inside rail",
    "Low draw +"
   ],
   [
    "1m+",
    "Inside rail",
    "Low draw slight"
   ]
  ],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "aw",
  "undulation": 0.05,
  "uphill_finish": 0.0,
  "wants": [
   "Early speed",
   "Low draw at sprint trips"
  ]
 },
 "epsom": {
  "camber": 0.9,
  "caution_flags": [
   "unbalanced_mover",
   "large_striding_horse",
   "first_time_here"
  ],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "1m": "stalls_position_matters",
   "1m4f": "wide_draw_disadvantage_tattenham",
   "5f": "high_draw_camber",
   "6f": "mixed"
  },
  "elevation": [
   60,
   56,
   51,
   46,
   42,
   40,
   44,
   50,
   56,
   62
  ],
  "layout": "horseshoe",
  "name": "Epsom",
  "running_styles": [
   "prominent",
   "balanced"
  ],
  "shape": "horseshoe",
  "sharpness": 0.6,
  "significant_features": [
   "Significant downhill gradient to Tattenham Corner",
   "Camber towards the far rail in the straight",
   "Quirky — some horses never handle it",
   "Rises to the line"
  ],
  "stalls": [
   [
    "5f",
    "Straight (downhill) course",
    "High draw + (camber)"
   ],
   [
    "1m–1m2f",
    "Inside",
    "Low slight"
   ],
   [
    "1m4f",
    "Inside",
    "Negligible"
   ]
  ],
  "straight_course_f": 0,
  "straight_f": 4,
  "surface": "turf",
  "undulation": 0.95,
  "uphill_finish": 0.45,
  "wants": [
   "Balanced horse that handles camber",
   "Stays after the downhill run"
  ]
 },
 "exeter": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 16,
  "circumference_furlongs": 16,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Exeter",
  "running_styles": [
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.35,
  "significant_features": [
   "Right-handed, hilly, stiff finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 3,
  "surface": "turf",
  "undulation": 0.7,
  "uphill_finish": 0.65,
  "wants": [
   "Stamina"
  ]
 },
 "fairyhouse": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 14,
  "circumference_furlongs": 14,
  "codes": "both",
  "conf": "high",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "square_oval",
  "name": "Fairyhouse",
  "running_styles": [
   "prominent",
   "stayer"
  ],
  "shape": "square_oval",
  "sharpness": 0.35,
  "significant_features": [
   "Right-handed, roughly square circuit",
   "Testing uphill finish",
   "Irish Grand National venue"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.45,
  "uphill_finish": 0.65,
  "wants": [
   "Stamina — stiff uphill finish",
   "Handles right-hand turns"
  ]
 },
 "fakenham": {
  "camber": 0.3,
  "caution_flags": [
   "large_striding_horse"
  ],
  "circuit_f": 8,
  "circumference_furlongs": 8,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "tight_oval",
  "name": "Fakenham",
  "running_styles": [
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.85,
  "significant_features": [
   "Sharp left-hander, one-mile circuit"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.3,
  "uphill_finish": 0.2,
  "wants": [
   "Handy types"
  ]
 },
 "ffos las": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "both",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Ffos Las",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.25,
  "significant_features": [
   "Flat, galloping left-hander"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 4,
  "surface": "turf",
  "undulation": 0.05,
  "uphill_finish": 0.0,
  "wants": [
   "Galloping types"
  ]
 },
 "fontwell park": {
  "camber": 0.3,
  "caution_flags": [
   "large_striding_horse"
  ],
  "circuit_f": 8,
  "circumference_furlongs": 8,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "F8",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "figure8",
  "name": "Fontwell Park",
  "running_styles": [
   "prominent"
  ],
  "shape": "figure8",
  "sharpness": 0.8,
  "significant_features": [
   "Figure-of-eight chase course, left-handed hurdles",
   "Uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.5,
  "uphill_finish": 0.45,
  "wants": [
   "Handy, balanced types"
  ]
 },
 "galway": {
  "camber": 0.45,
  "caution_flags": [
   "large_striding_horse",
   "hold_up_horse",
   "high_draw_7f_1m",
   "non_stayer_uphill"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "both",
  "conf": "high",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "1m": "low_draw_moderate",
   "1m2f+": "negligible",
   "7f": "low_draw_moderate"
  },
  "elevation": [
   62,
   57,
   50,
   43,
   37,
   34,
   43,
   57,
   72,
   86
  ],
  "layout": "tight_oval",
  "name": "Galway",
  "running_styles": [
   "prominent",
   "front_runner"
  ],
  "shape": "tight_oval",
  "sharpness": 0.85,
  "significant_features": [
   "Very sharp right-handed circuit",
   "Downhill run to the straight, then a steep climb",
   "Hold-up horses find it hard to make up ground"
  ],
  "stalls": [
   [
    "7f",
    "Inside rail",
    "Low draw +"
   ],
   [
    "1m–1m1f",
    "Inside rail",
    "Low draw +"
   ],
   [
    "1m4f+",
    "Inside rail",
    "Negligible"
   ]
  ],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.8,
  "uphill_finish": 0.9,
  "wants": [
   "Handy, balanced, quick into stride",
   "Stamina for the steep climb to the line",
   "Low draw 7f–1m"
  ]
 },
 "goodwood": {
  "camber": 0.4,
  "caution_flags": [
   "one_paced_horse",
   "unbalanced_mover"
  ],
  "circuit_f": 14,
  "circumference_furlongs": 14,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "1m+": "negligible",
   "5f": "low_draw_slight",
   "6f": "mixed"
  },
  "elevation": [
   52,
   57,
   55,
   48,
   44,
   47,
   53,
   57,
   58,
   60
  ],
  "layout": "loop",
  "name": "Goodwood",
  "running_styles": [
   "prominent",
   "strong_traveller"
  ],
  "shape": "loop",
  "sharpness": 0.5,
  "significant_features": [
   "Undulating, with a downhill run into the straight",
   "Tricky camber — traffic common in big fields",
   "Straight 6f sprint course"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 5,
  "surface": "turf",
  "undulation": 0.75,
  "uphill_finish": 0.5,
  "wants": [
   "Balance on the undulations",
   "High cruising speed"
  ]
 },
 "gowran park": {
  "camber": 0.25,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 11,
  "circumference_furlongs": 11,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Gowran Park",
  "running_styles": [
   "prominent",
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.45,
  "significant_features": [
   "Right-handed, undulating",
   "Uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.55,
  "uphill_finish": 0.6,
  "wants": [
   "Stamina for the rising finish"
  ]
 },
 "hamilton": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 13,
  "circumference_furlongs": 13,
  "codes": "flat",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   55,
   53,
   50,
   47,
   42,
   37,
   41,
   48,
   55,
   61
  ],
  "layout": "loop",
  "name": "Hamilton",
  "running_styles": [
   "prominent"
  ],
  "shape": "loop",
  "sharpness": 0.3,
  "significant_features": [
   "Straight 6f plus right-handed loop",
   "Undulating with a dip and stiff finish"
  ],
  "stalls": [],
  "straight_course_f": 6,
  "straight_f": 5,
  "surface": "turf",
  "undulation": 0.7,
  "uphill_finish": 0.7,
  "wants": [
   "Stamina for the stiff finish"
  ]
 },
 "haydock": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 13,
  "circumference_furlongs": 13,
  "codes": "both",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Haydock",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.2,
  "significant_features": [
   "Flat, fair, galloping left-hander"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 4.5,
  "surface": "turf",
  "undulation": 0.1,
  "uphill_finish": 0.1,
  "wants": [
   "Galloping types"
  ]
 },
 "hereford": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Hereford",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.5,
  "significant_features": [
   "Right-handed, fairly flat"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.1,
  "uphill_finish": 0.05,
  "wants": [
   "Handy types"
  ]
 },
 "hexham": {
  "camber": 0.3,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Hexham",
  "running_styles": [
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.5,
  "significant_features": [
   "Left-handed, very undulating, stiff finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.85,
  "uphill_finish": 0.8,
  "wants": [
   "Stamina — stiff climb"
  ]
 },
 "huntingdon": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Huntingdon",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.35,
  "significant_features": [
   "Flat right-handed oval"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.0,
  "uphill_finish": 0.0,
  "wants": [
   "Speed"
  ]
 },
 "kelso": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Kelso",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.55,
  "significant_features": [
   "Left-handed, long uphill run-in (chase)"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.3,
  "uphill_finish": 0.6,
  "wants": [
   "Stamina for the long run-in"
  ]
 },
 "kempton": {
  "camber": 0.1,
  "caution_flags": [
   "large_striding_horse"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "both",
  "conf": "high",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "1m+": "negligible",
   "5f": "low_draw_slight",
   "6f": "low_draw_slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Kempton",
  "running_styles": [
   "prominent",
   "handy"
  ],
  "shape": "oval",
  "sharpness": 0.45,
  "significant_features": [
   "Right-handed Polytrack (inner + outer loops)",
   "Flat — speed and position matter",
   "Also a right-handed jumps course"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 3,
  "surface": "aw",
  "undulation": 0.0,
  "uphill_finish": 0.0,
  "wants": [
   "Tactical speed",
   "Handles kickback"
  ]
 },
 "kilbeggan": {
  "camber": 0.3,
  "caution_flags": [
   "non_stayer_uphill",
   "poor_jumper"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "nh",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Kilbeggan",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.65,
  "significant_features": [
   "Right-handed, undulating jumps-only track",
   "Uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 1.5,
  "surface": "turf",
  "undulation": 0.6,
  "uphill_finish": 0.6,
  "wants": [
   "Handy, accurate jumpers",
   "Stamina for the rising finish"
  ]
 },
 "killarney": {
  "camber": 0.2,
  "caution_flags": [
   "large_striding_horse",
   "hold_up_horse"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "tight_oval",
  "name": "Killarney",
  "running_styles": [
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.7,
  "significant_features": [
   "Left-handed, sharp, fairly flat"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.2,
  "uphill_finish": 0.15,
  "wants": [
   "Handy types"
  ]
 },
 "laytown": {
  "camber": 0.1,
  "caution_flags": [
   "hold_up_horse"
  ],
  "circuit_f": 0,
  "circumference_furlongs": 0,
  "codes": "flat",
  "conf": "high",
  "country": "IRE",
  "direction": "S",
  "draw_bias": {
   "all": "varies"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "straight",
  "name": "Laytown",
  "running_styles": [
   "front_runner",
   "prominent"
  ],
  "shape": "straight",
  "sharpness": 0.0,
  "significant_features": [
   "Unique straight course on the beach",
   "Racing set by the tide — one meeting a year"
  ],
  "stalls": [
   [
    "6f–7f",
    "Straight beach course",
    "Varies with the tide and wind"
   ]
  ],
  "straight_course_f": 7,
  "straight_f": 7,
  "surface": "sand",
  "undulation": 0.05,
  "uphill_finish": 0.0,
  "wants": [
   "Early speed",
   "Handles sand"
  ]
 },
 "leicester": {
  "camber": 0.1,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 14,
  "circumference_furlongs": 14,
  "codes": "both",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   55,
   53,
   50,
   47,
   42,
   37,
   41,
   48,
   55,
   61
  ],
  "layout": "oval",
  "name": "Leicester",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.3,
  "significant_features": [
   "Right-handed, galloping",
   "Straight mile with a dip and rising finish"
  ],
  "stalls": [],
  "straight_course_f": 8,
  "straight_f": 5,
  "surface": "turf",
  "undulation": 0.45,
  "uphill_finish": 0.5,
  "wants": [
   "Galloping types with stamina"
  ]
 },
 "leopardstown": {
  "camber": 0.2,
  "caution_flags": [
   "high_draw_7f_1m",
   "non_stayer_uphill"
  ],
  "circuit_f": 14,
  "circumference_furlongs": 14,
  "codes": "both",
  "conf": "high",
  "country": "IRE",
  "direction": "L",
  "draw_bias": {
   "1m": "low_draw_slight",
   "1m2f+": "negligible",
   "7f": "low_draw_slight"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Leopardstown",
  "running_styles": [
   "prominent",
   "strong_traveller"
  ],
  "shape": "oval",
  "sharpness": 0.35,
  "significant_features": [
   "Left-handed, fair galloping track",
   "Short-ish straight that rises to the line",
   "Premier Flat and NH venue"
  ],
  "stalls": [
   [
    "7f–1m",
    "Inside rail",
    "Low draw slight edge"
   ],
   [
    "1m2f+",
    "Inside rail",
    "Negligible"
   ]
  ],
  "straight_course_f": 0,
  "straight_f": 2.5,
  "surface": "turf",
  "undulation": 0.4,
  "uphill_finish": 0.55,
  "wants": [
   "Tactical speed off the home turn",
   "Stamina up the rising straight"
  ]
 },
 "limerick": {
  "camber": 0.25,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 11,
  "circumference_furlongs": 11,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Limerick",
  "running_styles": [
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.4,
  "significant_features": [
   "Right-handed, undulating",
   "Testing uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2.5,
  "surface": "turf",
  "undulation": 0.55,
  "uphill_finish": 0.65,
  "wants": [
   "Stamina — stiff climb"
  ]
 },
 "lingfield": {
  "camber": 0.1,
  "caution_flags": [
   "large_striding_horse",
   "turf_form_not_transferable_to_aw"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "both",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "1m+": "negligible",
   "5f": "low_draw_slight",
   "6f": "low_draw_slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Lingfield",
  "running_styles": [
   "prominent",
   "handy"
  ],
  "shape": "oval",
  "sharpness": 0.6,
  "significant_features": [
   "Sharp left-handed Polytrack oval",
   "Separate undulating turf course with a stiff finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "aw",
  "undulation": 0.1,
  "uphill_finish": 0.0,
  "wants": [
   "Handy types"
  ]
 },
 "listowel": {
  "camber": 0.2,
  "caution_flags": [
   "large_striding_horse",
   "hold_up_horse"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "tight_oval",
  "name": "Listowel",
  "running_styles": [
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.7,
  "significant_features": [
   "Left-handed, sharp, fairly flat",
   "Often soft for the September festival"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.2,
  "uphill_finish": 0.2,
  "wants": [
   "Handy types",
   "Handles soft ground (autumn festival)"
  ]
 },
 "ludlow": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Ludlow",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.4,
  "significant_features": [
   "Right-handed, flat"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.1,
  "uphill_finish": 0.05,
  "wants": [
   "Speed"
  ]
 },
 "market rasen": {
  "camber": 0.15,
  "caution_flags": [],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Market Rasen",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.55,
  "significant_features": [
   "Right-handed, fairly sharp"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.25,
  "uphill_finish": 0.1,
  "wants": [
   "Handy types"
  ]
 },
 "musselburgh": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "both",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "5f": "high_draw_slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Musselburgh",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.55,
  "significant_features": [
   "Tight, flat right-hander"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 3.5,
  "surface": "turf",
  "undulation": 0.05,
  "uphill_finish": 0.0,
  "wants": [
   "Handy types"
  ]
 },
 "naas": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "L",
  "draw_bias": {
   "5f": "varies_with_stalls_side",
   "6f": "varies_with_stalls_side",
   "7f+": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Naas",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.3,
  "significant_features": [
   "Left-handed, galloping",
   "Straight sprint course",
   "Rising finish"
  ],
  "stalls": [
   [
    "5f–6f",
    "Straight course",
    "Varies with stalls side"
   ],
   [
    "7f+",
    "Round course, inside rail",
    "Negligible"
   ]
  ],
  "straight_course_f": 6,
  "straight_f": 3,
  "surface": "turf",
  "undulation": 0.45,
  "uphill_finish": 0.65,
  "wants": [
   "Stamina — stiff uphill finish"
  ]
 },
 "navan": {
  "camber": 0.25,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Navan",
  "running_styles": [
   "stayer",
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.35,
  "significant_features": [
   "Left-handed, undulating",
   "Stiff uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2.5,
  "surface": "turf",
  "undulation": 0.6,
  "uphill_finish": 0.7,
  "wants": [
   "Stamina — undulating with a stiff climb"
  ]
 },
 "newbury": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 15,
  "circumference_furlongs": 15,
  "codes": "both",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "1m+": "negligible",
   "5f": "low_draw_slight",
   "6f": "slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Newbury",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.2,
  "significant_features": [
   "Wide, galloping, fair",
   "Straight mile and long home straight"
  ],
  "stalls": [],
  "straight_course_f": 8,
  "straight_f": 5,
  "surface": "turf",
  "undulation": 0.15,
  "uphill_finish": 0.1,
  "wants": [
   "Galloping types"
  ]
 },
 "newcastle": {
  "camber": 0.1,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 14,
  "circumference_furlongs": 14,
  "codes": "both",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "straight_plus_oval",
  "name": "Newcastle",
  "running_styles": [
   "galloper",
   "strong_finisher"
  ],
  "shape": "straight_plus_oval",
  "sharpness": 0.3,
  "significant_features": [
   "Tapeta with a straight mile (rising)",
   "Left-handed jumps course"
  ],
  "stalls": [],
  "straight_course_f": 8,
  "straight_f": 4,
  "surface": "aw",
  "undulation": 0.05,
  "uphill_finish": 0.4,
  "wants": [
   "Stamina for the rising straight mile"
  ]
 },
 "newmarket": {
  "camber": 0.1,
  "caution_flags": [
   "sharp_track_specialist",
   "non_stayer_uphill"
  ],
  "circuit_f": 0,
  "circumference_furlongs": 0,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "S",
  "draw_bias": {
   "1m+": "negligible",
   "5f": "varies_with_stalls_side",
   "6f": "varies_with_stalls_side"
  },
  "elevation": [
   55,
   53,
   50,
   47,
   42,
   37,
   41,
   48,
   55,
   61
  ],
  "layout": "straight",
  "name": "Newmarket",
  "running_styles": [
   "galloper",
   "strong_traveller"
  ],
  "shape": "straight",
  "sharpness": 0.0,
  "significant_features": [
   "Wide straight course (Rowley Mile / July) — no turns up to 1m2f",
   "The Dip about 1f out, then uphill to the line"
  ],
  "stalls": [
   [
    "5f–1m",
    "Straight course — centre/either side",
    "Varies by stalls position"
   ],
   [
    "1m2f",
    "Straight",
    "Negligible"
   ]
  ],
  "straight_course_f": 10,
  "straight_f": 10,
  "surface": "turf",
  "undulation": 0.55,
  "uphill_finish": 0.65,
  "wants": [
   "Galloping, long-striding",
   "Stamina to climb out of the Dip"
  ]
 },
 "newton abbot": {
  "camber": 0.15,
  "caution_flags": [
   "large_striding_horse"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "tight_oval",
  "name": "Newton Abbot",
  "running_styles": [
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.8,
  "significant_features": [
   "Tight, flat left-hander"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.05,
  "uphill_finish": 0.0,
  "wants": [
   "Handy, quick types"
  ]
 },
 "nottingham": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Nottingham",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.25,
  "significant_features": [
   "Flat, fair, galloping left-hander"
  ],
  "stalls": [],
  "straight_course_f": 6,
  "straight_f": 4.5,
  "surface": "turf",
  "undulation": 0.1,
  "uphill_finish": 0.05,
  "wants": [
   "Galloping types"
  ]
 },
 "perth": {
  "camber": 0.15,
  "caution_flags": [],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Perth",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.55,
  "significant_features": [
   "Right-handed, flat, fairly sharp"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.1,
  "uphill_finish": 0.05,
  "wants": [
   "Handy types"
  ]
 },
 "plumpton": {
  "camber": 0.3,
  "caution_flags": [
   "large_striding_horse",
   "non_stayer_uphill"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   60,
   56,
   51,
   46,
   42,
   40,
   44,
   50,
   56,
   62
  ],
  "layout": "tight_oval",
  "name": "Plumpton",
  "running_styles": [
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.8,
  "significant_features": [
   "Sharp, undulating left-hander, downhill back straight",
   "Uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.7,
  "uphill_finish": 0.6,
  "wants": [
   "Handy, balanced types"
  ]
 },
 "pontefract": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 16,
  "circumference_furlongs": 16,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "1m": "low_draw_slight",
   "5f": "low_draw_moderate",
   "6f": "low_draw_moderate"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Pontefract",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.5,
  "significant_features": [
   "Left-handed, undulating",
   "Short, very stiff uphill straight"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.7,
  "uphill_finish": 0.9,
  "wants": [
   "Stamina — very stiff uphill finish"
  ]
 },
 "punchestown": {
  "camber": 0.3,
  "caution_flags": [
   "non_stayer_uphill",
   "poor_jumper"
  ],
  "circuit_f": 16,
  "circumference_furlongs": 16,
  "codes": "nh",
  "conf": "high",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   52,
   57,
   55,
   48,
   44,
   47,
   53,
   57,
   58,
   60
  ],
  "layout": "oval",
  "name": "Punchestown",
  "running_styles": [
   "prominent",
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.35,
  "significant_features": [
   "Right-handed, undulating",
   "Stiff uphill run to the line",
   "Home of the Festival — true stamina test"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.7,
  "uphill_finish": 0.7,
  "wants": [
   "Stamina",
   "Accurate jumping on the downhill fences"
  ]
 },
 "redcar": {
  "camber": 0.05,
  "caution_flags": [],
  "circuit_f": 14,
  "circumference_furlongs": 14,
  "codes": "flat",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Redcar",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.2,
  "significant_features": [
   "Flat, galloping, straight mile"
  ],
  "stalls": [],
  "straight_course_f": 8,
  "straight_f": 5,
  "surface": "turf",
  "undulation": 0.0,
  "uphill_finish": 0.0,
  "wants": [
   "Galloping types"
  ]
 },
 "ripon": {
  "camber": 0.2,
  "caution_flags": [],
  "circuit_f": 13,
  "circumference_furlongs": 13,
  "codes": "flat",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "5f": "varies_with_stalls_side",
   "6f": "varies_with_stalls_side"
  },
  "elevation": [
   52,
   57,
   55,
   48,
   44,
   47,
   53,
   57,
   58,
   60
  ],
  "layout": "oval",
  "name": "Ripon",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.4,
  "significant_features": [
   "Right-handed, slightly undulating",
   "Straight 6f — draw can matter"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 5,
  "surface": "turf",
  "undulation": 0.3,
  "uphill_finish": 0.1,
  "wants": [
   "Handy types"
  ]
 },
 "roscommon": {
  "camber": 0.2,
  "caution_flags": [
   "large_striding_horse"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Roscommon",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.55,
  "significant_features": [
   "Right-handed, fairly sharp"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.3,
  "uphill_finish": 0.3,
  "wants": [
   "Handy types"
  ]
 },
 "salisbury": {
  "camber": 0.15,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "loop",
  "name": "Salisbury",
  "running_styles": [
   "stayer"
  ],
  "shape": "loop",
  "sharpness": 0.3,
  "significant_features": [
   "Right-handed loop plus straight mile",
   "Stiff uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 8,
  "straight_f": 8,
  "surface": "turf",
  "undulation": 0.55,
  "uphill_finish": 0.7,
  "wants": [
   "Stamina — uphill final furlongs"
  ]
 },
 "sandown": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 13,
  "circumference_furlongs": 13,
  "codes": "both",
  "conf": "high",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Sandown",
  "running_styles": [
   "prominent",
   "strong_finisher"
  ],
  "shape": "oval",
  "sharpness": 0.35,
  "significant_features": [
   "Right-handed, stiff uphill finish",
   "Separate straight 5f course"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 4,
  "surface": "turf",
  "undulation": 0.6,
  "uphill_finish": 0.8,
  "wants": [
   "Stamina — stiff uphill finish"
  ]
 },
 "sedgefield": {
  "camber": 0.25,
  "caution_flags": [
   "large_striding_horse"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "tight_oval",
  "name": "Sedgefield",
  "running_styles": [
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.75,
  "significant_features": [
   "Sharp, undulating left-hander"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.55,
  "uphill_finish": 0.4,
  "wants": [
   "Handy types"
  ]
 },
 "sligo": {
  "camber": 0.3,
  "caution_flags": [
   "large_striding_horse",
   "non_stayer_uphill"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "tight_oval",
  "name": "Sligo",
  "running_styles": [
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.75,
  "significant_features": [
   "Right-handed, sharp and undulating",
   "Uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 1.5,
  "surface": "turf",
  "undulation": 0.6,
  "uphill_finish": 0.6,
  "wants": [
   "Handy types",
   "Stamina for the rising finish"
  ]
 },
 "southwell": {
  "camber": 0.1,
  "caution_flags": [
   "hold_up_horse"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "both",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "5f": "high_draw_slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Southwell",
  "running_styles": [
   "front_runner",
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.45,
  "significant_features": [
   "Left-handed Tapeta oval with straight 5f"
  ],
  "stalls": [],
  "straight_course_f": 5,
  "straight_f": 3,
  "surface": "aw",
  "undulation": 0.0,
  "uphill_finish": 0.0,
  "wants": [
   "Handles Tapeta kickback",
   "Early speed"
  ]
 },
 "stratford": {
  "camber": 0.15,
  "caution_flags": [
   "large_striding_horse"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "tight_oval",
  "name": "Stratford",
  "running_styles": [
   "prominent"
  ],
  "shape": "tight_oval",
  "sharpness": 0.8,
  "significant_features": [
   "Tight, flat left-hander"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.05,
  "uphill_finish": 0.0,
  "wants": [
   "Handy types"
  ]
 },
 "taunton": {
  "camber": 0.15,
  "caution_flags": [],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Taunton",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.6,
  "significant_features": [
   "Right-handed, fairly sharp"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.3,
  "uphill_finish": 0.3,
  "wants": [
   "Handy types"
  ]
 },
 "thirsk": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "flat",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "5f": "high_draw_slight",
   "6f": "high_draw_slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Thirsk",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.5,
  "significant_features": [
   "Left-handed oval with a straight 6f"
  ],
  "stalls": [],
  "straight_course_f": 6,
  "straight_f": 4,
  "surface": "turf",
  "undulation": 0.2,
  "uphill_finish": 0.1,
  "wants": [
   "Handy types"
  ]
 },
 "thurles": {
  "camber": 0.25,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Thurles",
  "running_styles": [
   "prominent",
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.5,
  "significant_features": [
   "Right-handed, undulating",
   "Uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.55,
  "uphill_finish": 0.6,
  "wants": [
   "Stamina for the rising finish"
  ]
 },
 "tipperary": {
  "camber": 0.2,
  "caution_flags": [
   "large_striding_horse",
   "hold_up_horse"
  ],
  "circuit_f": 9,
  "circumference_furlongs": 9,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "L",
  "draw_bias": {
   "1m+": "negligible",
   "5f": "low_draw_slight",
   "6f": "low_draw_slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "tight_oval",
  "name": "Tipperary",
  "running_styles": [
   "prominent",
   "front_runner"
  ],
  "shape": "tight_oval",
  "sharpness": 0.7,
  "significant_features": [
   "Left-handed, sharp",
   "Flat — speed and handiness count"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.2,
  "uphill_finish": 0.2,
  "wants": [
   "Handy, quick types"
  ]
 },
 "towcester": {
  "camber": 0.2,
  "caution_flags": [
   "non_stayer_uphill"
  ],
  "circuit_f": 14,
  "circumference_furlongs": 14,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Towcester",
  "running_styles": [
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.35,
  "significant_features": [
   "Right-handed, very stiff uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 3,
  "surface": "turf",
  "undulation": 0.85,
  "uphill_finish": 0.95,
  "wants": [
   "Real stamina — very stiff uphill finish"
  ]
 },
 "tramore": {
  "camber": 0.35,
  "caution_flags": [
   "large_striding_horse",
   "hold_up_horse",
   "non_stayer_uphill"
  ],
  "circuit_f": 8,
  "circumference_furlongs": 8,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   60,
   56,
   51,
   46,
   42,
   40,
   44,
   50,
   56,
   62
  ],
  "layout": "tight_oval",
  "name": "Tramore",
  "running_styles": [
   "prominent",
   "front_runner"
  ],
  "shape": "tight_oval",
  "sharpness": 0.9,
  "significant_features": [
   "Very sharp right-handed circuit",
   "Undulating with an uphill finish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 1.5,
  "surface": "turf",
  "undulation": 0.7,
  "uphill_finish": 0.7,
  "wants": [
   "Very handy, balanced types",
   "Stamina for the climb"
  ]
 },
 "uttoxeter": {
  "camber": 0.15,
  "caution_flags": [],
  "circuit_f": 11,
  "circumference_furlongs": 11,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   52,
   57,
   55,
   48,
   44,
   47,
   53,
   57,
   58,
   60
  ],
  "layout": "oval",
  "name": "Uttoxeter",
  "running_styles": [
   "stayer"
  ],
  "shape": "oval",
  "sharpness": 0.4,
  "significant_features": [
   "Left-handed, undulating"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.45,
  "uphill_finish": 0.2,
  "wants": [
   "Stamina"
  ]
 },
 "warwick": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 13,
  "circumference_furlongs": 13,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   52,
   57,
   55,
   48,
   44,
   47,
   53,
   57,
   58,
   60
  ],
  "layout": "oval",
  "name": "Warwick",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.4,
  "significant_features": [
   "Left-handed, sharp-ish"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2.5,
  "surface": "turf",
  "undulation": 0.3,
  "uphill_finish": 0.2,
  "wants": [
   "Speed, handiness"
  ]
 },
 "wetherby": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "both",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Wetherby",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.35,
  "significant_features": [
   "Left-handed, fair, slightly undulating"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 3,
  "surface": "turf",
  "undulation": 0.3,
  "uphill_finish": 0.3,
  "wants": [
   "Galloping types"
  ]
 },
 "wexford": {
  "camber": 0.25,
  "caution_flags": [
   "large_striding_horse"
  ],
  "circuit_f": 10,
  "circumference_furlongs": 10,
  "codes": "both",
  "conf": "medium",
  "country": "IRE",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Wexford",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.55,
  "significant_features": [
   "Right-handed, fairly sharp"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.4,
  "uphill_finish": 0.4,
  "wants": [
   "Handy types"
  ]
 },
 "wincanton": {
  "camber": 0.1,
  "caution_flags": [],
  "circuit_f": 11,
  "circumference_furlongs": 11,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "R",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50,
   50,
   50,
   50,
   51,
   53,
   56,
   60,
   64,
   68
  ],
  "layout": "oval",
  "name": "Wincanton",
  "running_styles": [
   "prominent"
  ],
  "shape": "oval",
  "sharpness": 0.4,
  "significant_features": [
   "Right-handed, fairly fast track"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "turf",
  "undulation": 0.3,
  "uphill_finish": 0.3,
  "wants": [
   "Speed, accurate jumping"
  ]
 },
 "windsor": {
  "camber": 0.1,
  "caution_flags": [
   "large_striding_horse",
   "first_time_here"
  ],
  "circuit_f": 12,
  "circumference_furlongs": 12,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "F8",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "figure8",
  "name": "Windsor",
  "running_styles": [
   "handy",
   "balanced"
  ],
  "shape": "figure8",
  "sharpness": 0.6,
  "significant_features": [
   "Figure-of-eight (only right-hand bends raced on the Flat)",
   "Flat — speed track"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 5,
  "surface": "turf",
  "undulation": 0.05,
  "uphill_finish": 0.0,
  "wants": [
   "Handy, balanced types"
  ]
 },
 "wolverhampton": {
  "camber": 0.1,
  "caution_flags": [
   "large_striding_horse",
   "high_draw_sprint"
  ],
  "circuit_f": 8.75,
  "circumference_furlongs": 8.75,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "1m+": "negligible",
   "5f": "low_draw_moderate",
   "6f": "low_draw_slight"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "tight_oval",
  "name": "Wolverhampton",
  "running_styles": [
   "prominent",
   "handy"
  ],
  "shape": "tight_oval",
  "sharpness": 0.8,
  "significant_features": [
   "Tight left-handed Tapeta oval",
   "Handiness key"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 2,
  "surface": "aw",
  "undulation": 0.0,
  "uphill_finish": 0.0,
  "wants": [
   "Handy, sharp types"
  ]
 },
 "worcester": {
  "camber": 0.05,
  "caution_flags": [],
  "circuit_f": 13,
  "circumference_furlongs": 13,
  "codes": "nh",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Worcester",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.25,
  "significant_features": [
   "Flat, galloping left-hander by the river"
  ],
  "stalls": [],
  "straight_course_f": 0,
  "straight_f": 3,
  "surface": "turf",
  "undulation": 0.0,
  "uphill_finish": 0.0,
  "wants": [
   "Galloping types"
  ]
 },
 "yarmouth": {
  "camber": 0.05,
  "caution_flags": [],
  "circuit_f": 13,
  "circumference_furlongs": 13,
  "codes": "flat",
  "conf": "medium",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "all": "negligible"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "oval",
  "name": "Yarmouth",
  "running_styles": [
   "galloper"
  ],
  "shape": "oval",
  "sharpness": 0.25,
  "significant_features": [
   "Flat, galloping, straight mile"
  ],
  "stalls": [],
  "straight_course_f": 8,
  "straight_f": 5,
  "surface": "turf",
  "undulation": 0.0,
  "uphill_finish": 0.0,
  "wants": [
   "Galloping types"
  ]
 },
 "york": {
  "camber": 0.1,
  "caution_flags": [
   "extreme_hold_up_big_field"
  ],
  "circuit_f": 16,
  "circumference_furlongs": 16,
  "codes": "flat",
  "conf": "high",
  "country": "GB",
  "direction": "L",
  "draw_bias": {
   "1m+": "negligible",
   "5f": "high_draw_slight",
   "6f": "mixed"
  },
  "elevation": [
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0,
   50.0
  ],
  "layout": "horseshoe",
  "name": "York",
  "running_styles": [
   "galloper"
  ],
  "shape": "horseshoe",
  "sharpness": 0.2,
  "significant_features": [
   "Flat, fair, galloping left-hand horseshoe",
   "Long straight — true test"
  ],
  "stalls": [],
  "straight_course_f": 7,
  "straight_f": 5,
  "surface": "turf",
  "undulation": 0.05,
  "uphill_finish": 0.0,
  "wants": [
   "Genuine gallopers"
  ]
 }
};
